background: WHITE_STAINED_GLASS_PANE
##Display on Main GUI

back-item:
  item: FLOWER_BANNER_PATTERN
  name: "&cBack"
  glow: true
  lore:
    - "&7Click to Back"


team-join: "&aYou have joined {team} Team"
team-closed: "&cYou are not invited to join {team} team"
team-already-joined: "&cYou are already in {team} Team"





