
# This allow player to directly open gui through /team command or its aliases
use-native-command: true # Required Server Restart to apply changes

#For Bedrock Form
back-button:
  lines:
    - "&cBack"
    - "&aClick to Back"
  image:
    enabled: false
    url: " "

#Possible Placeholder [{player},{uuid}]
# Avatar: "https://crafatar.com/avatars/{uuid}?size=128&overlay"
Avatar: "https://mc-heads.net/avatar/%skinsrestorer_texture_id_or_steve%.png"
# Note It is recommended to use %skinsrestorer_texture_id_or_steve% as placeholder for avatar

#Don't change this value unless you know what it means
version: 2.0