name: BetterTeamGUI
version: '1.0.1'
main: me.justlime.betterTeamGUI.BetterTeamGUI
api-version: '1.21'
depend:
  - BetterTeams

commands:
  teams:
    description: Opens the teams gui
    usage: /teams
    permission: betterteamgui.use.teams
    default: true

