name: BetterTeamGUI
version: '1.2'
main: me.justlime.betterTeamGUI.BetterTeamGUI
api-version: '1.13'
description: "A Addon plugin for BetterTeams of (v4.10.0)"
author: ItsJustLime
website: https://discord.gg/rVsUJ4keZN

depend:
  - BetterTeams
commands:
  teams:
    description: Opens the teams gui
    usage: /teams
    permission: betterteamgui.use.teams
    default: true
permissions:
  betterteamgui.use.*:
    description: Allows the player to use the commands
    default: true
    children:
      - betterteamgui.use.warps: true
      - betterteamgui.use.balance: true
      - betterteamgui.use.members: true
      - betterteamgui.use.ally: true
      - betterteamgui.use.view: true

  betterteamgui.use.teams:
    description: Allows the player to use the teams command
    default: true

  betterteamgui.use.warps:
    description: Allows the player to open the warps gui
    default: true

  betterteamgui.use.balance:
    description: Allows the player to open the balance gui
    default: true

  betterteamgui.use.members:
    description: Allows the player to open the members gui
    default: true

  betterteamgui.use.ally:
    description: Allows the player to open the ally gui
    default: true

  betterteamgui.use.view:
    description: Allows the player to open the other team view gui
    default: true

  betterteamgui.admin.reload:
    description: Allows the player to use admin commands
    default: op

