name: BetterTeamGUI
version: '1.1'
main: me.justlime.betterTeamGUI.BetterTeamGUI
api-version: '1.13'
depend:
  - BetterTeams

commands:
  team:
    description: Opens the team gui
    usage: /team
    permission: betterteamgui.use.team
    default: true

  teams:
    description: Opens the teams gui
    usage: /teams
    permission: betterteamgui.use.teams
    default: true

